[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vaantamil"
version = "0.1.0"
description = "Tamil analyzer"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
